use crate::*;

/// Events to be generated by the contract according to NEP-297

#[derive(Serialize, Debug)]
#[serde(crate = "near_sdk::serde")]
pub struct FtLockupNew {
    pub token_account_id: AccountId,
}

#[derive(Serialize, Debug)]
#[serde(crate = "near_sdk::serde")]
pub struct FtLockupAddToDepositWhitelist {
    pub account_ids: Vec<AccountId>,
}

#[derive(Serialize, Debug)]
#[serde(crate = "near_sdk::serde")]
pub struct FtLockupRemoveFromDepositWhitelist {
    pub account_ids: Vec<AccountId>,
}

#[derive(Serialize, Debug)]
#[serde(crate = "near_sdk::serde")]
pub struct FtLockupAddToDraftOperatorsWhitelist {
    pub account_ids: Vec<AccountId>,
}

#[derive(Serialize, Debug)]
#[serde(crate = "near_sdk::serde")]
pub struct FtLockupRemoveFromDraftOperatorsWhitelist {
    pub account_ids: Vec<AccountId>,
}

#[derive(Serialize, Debug)]
#[serde(crate = "near_sdk::serde")]
#[serde(tag = "event", content = "data")]
#[serde(rename_all = "snake_case")]
pub(crate) enum EventKind {
    FtLockupNew(FtLockupNew),
    FtLockupAddToDepositWhitelist(FtLockupAddToDepositWhitelist),
    FtLockupRemoveFromDepositWhitelist(FtLockupRemoveFromDepositWhitelist),
    FtLockupAddToDraftOperatorsWhitelist(FtLockupAddToDraftOperatorsWhitelist),
    FtLockupRemoveFromDraftOperatorsWhitelist(FtLockupRemoveFromDraftOperatorsWhitelist),
}

#[derive(Serialize, Debug)]
#[serde(crate = "near_sdk::serde")]
#[serde(rename_all = "snake_case")]
pub(crate) struct NearEvent {
    standard: String,
    version: String,
    #[serde(flatten)]
    event_kind: EventKind,
}

impl From<EventKind> for NearEvent {
    fn from(event_kind: EventKind) -> Self {
        Self {
            standard: PACKAGE_NAME.into(),
            version: VERSION.into(),
            event_kind,
        }
    }
}

impl NearEvent {
    fn to_json_string(&self) -> String {
        serde_json::to_string(self).unwrap()
    }

    fn to_json_event_string(&self) -> String {
        format!("EVENT_JSON:{}", self.to_json_string())
    }

    pub(crate) fn emit(self) {
        log!("{}", &self.to_json_event_string());
    }
}

pub(crate) fn emit(event_kind: EventKind) {
    NearEvent::from(event_kind).emit();
}

#[cfg(test)]
mod tests {
    use super::*;
    use near_sdk::serde_json::json;
    use near_sdk::test_utils::VMContextBuilder;
    use near_sdk::{test_utils, testing_env, MockedBlockchain, VMContext};

    pub fn get_context() -> VMContext {
        VMContextBuilder::new().is_view(true).build()
    }

    #[test]
    fn test_ft_lockup_init() {
        testing_env!(get_context());

        let token_account_id = "token.near".into();
        emit(EventKind::FtLockupNew(FtLockupNew { token_account_id }));
        assert_eq!(
            test_utils::get_logs()[0],
            format!(
                r"EVENT_JSON:{}",
                json!({
                    "standard": PACKAGE_NAME,
                    "version": VERSION,
                    "event": "ft_lockup_new",
                    "data": { "token_account_id": "token.near" },
                })
                .to_string(),
            )
        );
    }

    #[test]
    fn test_ft_lockup_add_to_deposit_whitelist() {
        testing_env!(get_context());

        let account_ids: Vec<AccountId> = vec!["alice.near", "bob.near"]
            .iter()
            .map(|&x| x.into())
            .collect();
        emit(EventKind::FtLockupAddToDepositWhitelist(
            FtLockupAddToDepositWhitelist { account_ids },
        ));
        assert_eq!(
            test_utils::get_logs()[0],
            format!(
                r"EVENT_JSON:{}",
                json!({
                    "standard": PACKAGE_NAME,
                    "version": VERSION,
                    "event": "ft_lockup_add_to_deposit_whitelist",
                    "data": { "account_ids": ["alice.near", "bob.near"] },
                })
                .to_string(),
            )
        );
    }

    #[test]
    fn test_ft_lockup_remove_from_deposit_whitelist() {
        testing_env!(get_context());

        let account_ids: Vec<AccountId> = vec!["alice.near", "bob.near"]
            .iter()
            .map(|&x| x.into())
            .collect();
        emit(EventKind::FtLockupRemoveFromDepositWhitelist(
            FtLockupRemoveFromDepositWhitelist { account_ids },
        ));
        assert_eq!(
            test_utils::get_logs()[0],
            format!(
                r"EVENT_JSON:{}",
                json!({
                    "standard": PACKAGE_NAME,
                    "version": VERSION,
                    "event": "ft_lockup_remove_from_deposit_whitelist",
                    "data": { "account_ids": ["alice.near", "bob.near"] },
                })
                .to_string(),
            )
        );
    }

    #[test]
    fn test_ft_lockup_add_to_draft_operators_whitelist() {
        testing_env!(get_context());

        let account_ids: Vec<AccountId> = vec!["alice.near", "bob.near"]
            .iter()
            .map(|&x| x.into())
            .collect();
        emit(EventKind::FtLockupAddToDraftOperatorsWhitelist(
            FtLockupAddToDraftOperatorsWhitelist { account_ids },
        ));
        assert_eq!(
            test_utils::get_logs()[0],
            format!(
                r"EVENT_JSON:{}",
                json!({
                    "standard": PACKAGE_NAME,
                    "version": VERSION,
                    "event": "ft_lockup_add_to_draft_operators_whitelist",
                    "data": { "account_ids": ["alice.near", "bob.near"] },
                })
                .to_string(),
            )
        );
    }

    #[test]
    fn test_ft_lockup_remove_from_draft_operators_whitelist() {
        testing_env!(get_context());

        let account_ids: Vec<AccountId> = vec!["alice.near", "bob.near"]
            .iter()
            .map(|&x| x.into())
            .collect();
        emit(EventKind::FtLockupRemoveFromDraftOperatorsWhitelist(
            FtLockupRemoveFromDraftOperatorsWhitelist { account_ids },
        ));
        assert_eq!(
            test_utils::get_logs()[0],
            format!(
                r"EVENT_JSON:{}",
                json!({
                    "standard": PACKAGE_NAME,
                    "version": VERSION,
                    "event": "ft_lockup_remove_from_draft_operators_whitelist",
                    "data": { "account_ids": ["alice.near", "bob.near"] },
                })
                .to_string(),
            )
        );
    }
}
